### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by BlackRussian** [BlackRussian/nextSIS#1]
![image](https://cloud.githubusercontent.com/assets/1154698/5945087/f33e5402-a6f9-11e4-8468-8438abdc13a0.png)

**Comment by nitro2001** [comment]
Whats the issue?

**Comment by BlackRussian** [comment]
There is a big notification covering the background.

**Comment by nitro2001** [comment]
I thought thats how it was suppose to look?

**Comment by BlackRussian** [comment]
No this should have a small alert area at the top only
